In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
import os
current_directory = os.getcwd()
print("current path:", current_directory)

当前路径: /root/autodl-tmp/hdcbc


In [3]:
nyc_check_in = gpd.read_file(r'shp/nyc_checkin_sticc3.shp',engine='pyogrio')
nyc_check_in.head(1)

venueId  userId  gender  friend_num  follow_num  \
0  42829c80f964a5202f221fe3    1409  female       487.0        98.0   

    latitude  longitude venueCateg week  hour  week_attr  category  n_pt_0  \
0  40.754239 -73.985473     Office  Tue     8          2         3    3201   

   n_pt_1  n_pt_2                    geometry  
0      11      16  POINT (-73.98547 40.75424)

In [4]:
nyc_check_in.groupby("venueCateg").count().sort_values("venueId").tail(1)

venueId  userId  gender  friend_num  follow_num  latitude  \
venueCateg                                                                  
Home (private)     2880    2880    2880        2880        2880      2880   

                longitude  week  hour  week_attr  category  n_pt_0  n_pt_1  \
venueCateg                                                                   
Home (private)       2880  2880  2880       2880      2880    2880    2880   

                n_pt_2  geometry  
venueCateg                        
Home (private)    2880      2880

In [5]:
venueCateg_list = ["Office", "Home (private)"]
venueId_list = pd.DataFrame(nyc_check_in.venueId.unique()).sample(frac=0.3).values.squeeze()
nyc_check_hdcbc = nyc_check_in[(nyc_check_in.venueCateg.isin(venueCateg_list))&(nyc_check_in.venueId.isin(venueId_list))]
print(nyc_check_hdcbc.shape)
nyc_check_hdcbc.head(1)

(1243, 16)


venueId  userId gender  friend_num  follow_num  \
59  49bee48bf964a520ed541fe3     260   male       189.0        90.0   

     latitude  longitude venueCateg week  hour  week_attr  category  n_pt_0  \
59  40.756086 -73.989833     Office  Wed    14          3         3      64   

    n_pt_1  n_pt_2                    geometry  
59      62      63  POINT (-73.98983 40.75609)

In [6]:
def return_week(x):
    if x == "Mon":
        return 1
    elif x == "Tue":
        return 2
    elif x == "Wed":
        return 3
    elif x == "Thu":
        return 4
    elif x == "Fri":
        return 5
    elif x == "Sat":
        return 6
    elif x == "Sun":
        return 7
    
def return_category(x):
    if x == "Gym":
        return 1
    elif x == "Coffee Shop":
        return 2
    elif x == "Office":
        return 3
    elif x == "Home (private)":
        return 4
    elif x == "Subway":
        return 5

nyc_check_hdcbc["week_attr"] = nyc_check_hdcbc["week"].apply(lambda x: return_week(x))
nyc_check_hdcbc["category"] = nyc_check_hdcbc["venueCateg"].apply(lambda x: return_category(x))
nyc_check_hdcbc = nyc_check_hdcbc.reset_index().drop("index", axis=1)

/root/miniconda3/lib/python3.8/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/root/miniconda3/lib/python3.8/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)


In [7]:
nyc_check_hdcbc.head(1)

venueId  userId gender  friend_num  follow_num   latitude  \
0  49bee48bf964a520ed541fe3     260   male       189.0        90.0  40.756086   

   longitude venueCateg week  hour  week_attr  category  n_pt_0  n_pt_1  \
0 -73.989833     Office  Wed    14          3         3      64      62   

   n_pt_2                    geometry  
0      63  POINT (-73.98983 40.75609)

In [8]:
nyc_check_hdcbc[["latitude","longitude","week_attr", "hour","category"]].to_csv(
    r'dataset/nyc_checkin.csv', 
    header=True,  
    index=False,  
    sep=','
)

# OPENCSV

In [70]:
import numpy as np

#import arff


import pandas

import os
import pickle


In [45]:

def noise_generate(data):

    original_data=data.values
    x_min, x_max = original_data[:, 0].min(), original_data[:, 0].max()
    y_min, y_max = original_data[:, 1].min(), original_data[:, 1].max()


    length=int(original_data.shape[0]/10)
    noise_x = np.random.uniform(x_min, x_max, length)
    noise_y = np.random.uniform(y_min, y_max, length)
    noise_label = np.full(length, -1)

    #print(original_data)
    nose=np.column_stack((noise_x, noise_y, noise_label))

    noisy_data = np.vstack((original_data,nose))
    pdf=pandas.DataFrame(noisy_data)

    return pdf


In [12]:
import pickle
import pandas

folder_path=r'dataset/'

file_list = os.listdir(folder_path)


data={}
for file_name in file_list:
    file_path = os.path.join(folder_path, file_name)
    if file_name.startswith('.'):
        continue
    file_name=file_name.replace('.csv','')

    print(file_path)

    if os.path.isfile(file_path):

        try:
            d=pandas.read_csv(file_path)
            
           
            # columns_to_keep = [col for col in d.columns if col not in ["week_attr", "hour"]]

           
            # d = d[columns_to_keep]
            
            
            #print(d.values[:,0].min())

            #d=noise_generate(d)


            data[file_name]=d
            print(d.head())
        except ZeroDivisionError as e:

            print("Division by zero:", e)
        except ValueError as e:

            print("Value error:", e)
        except Exception as e:

            print("An error occurred:", e)

data_list={}
for key in data.keys():

    data_list[key] = data[key]




print(len(data_list))

with open(r'cache/data_csv.pkl','wb') as file:
    pickle.dump(data_list,file)



dataset/nyc_checkin.csv
    latitude  longitude  week_attr  hour  category
0  40.756086 -73.989833          3    14         3
1  40.755637 -73.990566          4    17         3
2  40.756181 -73.990680          5    13         3
3  40.755342 -73.989877          2    19         3
4  40.756211 -73.989022          5    10         3
1


In [34]:
!python main_one.py

HDCBC
calculating core distance
building reachability matrix
performing hdbscan
/root/miniconda3/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
ars: 0.6200077767999403
nmi: 0.6058544318374705
acc: 0.8938053097345132


In [21]:
!python main.py

[3 3 3 ... 3 3 3]
calculating DCM
building_ckDtree
calculating core distance
building reachability matrix
performing hdbscan
/root/miniconda3/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
[1 1 1 ... 1 1 1]
0.2075155497426152
[1 1 1 ... 1 1 1]
calculating core distance
building reachability matrix
performing hdbscan
/root/miniconda3/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
[1 1 1 ... 1 1 1]
0.4604720181509145
[1 1 1 ... 1 1 1]
calculating core distance
building reachability matrix
performing hdbscan
/root/miniconda3/lib/python3.8/site-packages/sklearn/cluster/_k